version: "3.9"
services:
  db:
    container_name: mysql_atelier
    build:
      context: ./
      dockerfile: docker-config/mysql/Dockerfile
    environment:
      - MYSQL_ALLOW_LOCAL_INFILE=1
      - MYSQL_DATABASE=good_lock
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - ${MYSQL_PORT_CONTAINER}:3306
    volumes:
      - mysql_data_atelier:/var/lib/mysql
  phpmyadmin:
    container_name: pma_atelier
    build:
      context: ./
      dockerfile: docker-config/pma/Dockerfile
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=500M
      - POST_MAX_SIZE=500M
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT_CONTAINER}:80
volumes:
  mysql_data_atelier:
